<?php

/**
 * @file
 * Install hooks for this module.
 */

/**
 * Implements hook_uninstall().
 */
function islandora_confirm_indexed_uninstall() {
  variable_del('islandora_confirm_indexed_log_file_path');
  variable_del('islandora_confirm_indexed_pid_offset');
  variable_del('islandora_confirm_indexed_entry_delimiter');
  variable_del('islandora_confirm_indexed_include_timestamp');
  variable_del('islandora_confirm_indexed_include_success');
}
